// Data below generated by running the following on TWI table of contents (as of 2026-04-20)
//
// function getVolumeWrapperId(element) {
//   const parent = element.closest('.volume-wrapper');
//   return parent ? parent.id : null;
// }
// JSON.stringify(Array.from(document.querySelectorAll(".body-web.table-cell a")).map((e, i) => ({
//     chapterIndex: i,
//     chapterLink: e.href,
//     chapterName: e.innerText,
//     volumeId: getVolumeWrapperId(e),
// })), undefined, 2)

import type { ChapterData } from "../types";
import chapterData from "./chapters.json";

export const CHAPTER_DATA = chapterData as ChapterData[];
